name: Deploy Code to Release Branch
on:
  workflow_dispatch:

jobs:
  build:
    name: Push to Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary production deployment workflow will trigger to build the dependencies.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: .
          clean: false
          single-commit: true
# name: Build and Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout master branch
#         uses: actions/checkout@v2
#         with:
#           ref: master
#       - name: Use Node.js 16.x
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16.x'
#       - name: Install dependencies
#         run: npm install
#       - name: Build
#         run: npm run build
#       - name: Commit files
#         run: |
#           cd dist
#           git init
#           git config --global user.name "${{ github.actor }}"
#           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
#           git add .
#           git commit -m "deploy to Github pages"
#           git push -f origin master:gh-pages 
#           echo 🤘 deploy gh-pages complete.

#       - name: Checkout gh-pages branch
#         uses: actions/checkout@v2
#         with:
#           ref: gh-pages
#           create-branch: true
#       - name: Copy build files
#         run: cp -r dist/* .
#       - name: Commit changes
#         run: |
#           git config --global user.name "${{ github.actor }}"
#           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
#           git add .
#           git commit -m "Deploy"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
